[project]
name = "leviathan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cosmpy>=0.11.2",
    "ecdsa>=0.19.1",
    "fastapi>=0.128.0",
    "httpx>=0.28.1",
    "ollama>=0.6.1",
    "pandas>=2.0.0",
    "pydantic-settings>=2.12.0",
    "python-multipart>=0.0.22",
    "pyyaml>=6.0.3",
    "streamlit>=1.53.1",
    "uvicorn>=0.40.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.2",
]
